// Catálogo de cuentas del usuario (cuentas de detalle, listas para contabilizar).
// Generado a partir del catálogo estándar salvadoreño proporcionado.
// tipo_saldo: "deudor" (Activo, Costo, Gasto) o "acreedor" (Pasivo, Capital, Ingreso)

export const CATALOGO_COMPLETO = [
  { codigo: "110101", nombre: "Caja General", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "110102", nombre: "Caja Chica", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11010301", nombre: "Banco Industrial", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11010302", nombre: "Banco Agrícola", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11010303", nombre: "Banco Cuscatlán", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11010304", nombre: "Banco Promerica", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11010305", nombre: "Banco Davivienda", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11010306", nombre: "Banco Azul", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11010307", nombre: "Bac Credomatic", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11010308", nombre: "Sociedad De Ahorro Y Crédito Ahcr S.A. De C.V.", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11010401", nombre: "Banco Industrial", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11010402", nombre: "Banco Agrícola", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11010403", nombre: "Banco Cuscatlán", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11010404", nombre: "Banco Promerica", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11010405", nombre: "Banco Davivienda", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11010406", nombre: "Banco Azul", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11010407", nombre: "Bac Credomatic", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11010408", nombre: "Sociedad De Ahorro Y Crédito Ahcr S.A. De C.V.", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11010501", nombre: "Moneda Extranjera", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11010502", nombre: "Reportos", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11010503", nombre: "Depósito A Plazo Menores 90 Días", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11010504", nombre: "Certificados De Inversión", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11010505", nombre: "Venta Con Tarjeta De Crédito Y Tarjeta De Débito", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11010506", nombre: "Otros", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "110201", nombre: "Depósitos A Plazo", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11030101", nombre: "Nacionales", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11030102", nombre: "Extranjeros", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11030201", nombre: "Letras De Cambio", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11030202", nombre: "Pagaré", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11030203", nombre: "Intereses Por Cobrar", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11030204", nombre: "Otros Documentos Por Cobrar", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11030301", nombre: "Anticipos A Proveedores", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11030302", nombre: "Deudores Varios", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11030303", nombre: "Depósitos En Garantía", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11030401", nombre: "Préstamos A Empleados", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11030402", nombre: "Descuentos A Empleados", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11030403", nombre: "Anticipo De Sueldos", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "1103050101", nombre: "Préstamos A Accionistas", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11030502", nombre: "Otras Cuentas Por Cobrar A Partes Relacionadas", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "110306", nombre: "Remanente De Iva", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "110401", nombre: "Provisión Para Cuentas Incobrables", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "110501", nombre: "Pago A Cuenta Del Presente Ejercicio", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "110502", nombre: "Excedente Pago A Cuenta Del Ejercicio Anterior", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "110601", nombre: "Iva Por Compras Locales", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "110602", nombre: "Iva Por Importaciones", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "110603", nombre: "Iva Por Liquidar", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "110604", nombre: "1% De Iva Retenido", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "110605", nombre: "1% Iva Percibido", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "110606", nombre: "2% Anticipo Iva", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "110607", nombre: "Remanente De Iva", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "110701", nombre: "De Producto Para La Venta", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "110702", nombre: "De Producto Terminado", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "110703", nombre: "Producto En Proceso", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "110704", nombre: "Materiales Directos", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "110705", nombre: "Consumibles", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "110706", nombre: "Pedidos En Tránsito", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "110707", nombre: "Otros", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "110802", nombre: "Deterioro De Valor De Producto Terminado", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "110803", nombre: "Deterioro De Valor De Productos En Proceso", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "110804", nombre: "Deterioro De Valor De Materiales", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "110805", nombre: "Deterioro De Valor De Consumibles", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11090101", nombre: "Anticipos De Vacaciones", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11090102", nombre: "Anticipos De Aguinaldos", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11080103", nombre: "Otros Beneficios A Empleados Pagados Por Anticipado", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11090201", nombre: "Primas De Seguro En Vigor", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11090301", nombre: "Arrendamientos Pagados Por Adelantado", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11090401", nombre: "Papelería Y Útiles De Oficina", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11090501", nombre: "Combustible Y Lubricantes", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11090601", nombre: "Servicios Tecnicos Y Profesionales", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11090602", nombre: "Intereses Pagados Por Anticipado", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11090603", nombre: "Higiene Y Seguridad Industrial", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "11090604", nombre: "Otros Gastos Pagados Por Anticipado", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120101", nombre: "Cuentas Por Cobrar A Largo Plazo", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120201", nombre: "Depósitos En Garantía", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120301", nombre: "Terrenos", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120302", nombre: "Edificaciones", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120303", nombre: "Instalaciones", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120304", nombre: "Mobiliario Y Equipo De Oficina", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120305", nombre: "Maquinaría Y Equipo", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120306", nombre: "Equipo De Transporte", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120307", nombre: "Herramientas Y Repuestos", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120308", nombre: "Otros Equipos Propios", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120309", nombre: "Construcciones En Proceso", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120310", nombre: "Equipo En Instalación", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120401", nombre: "Depreciación Acumulada De Edificaciones", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120402", nombre: "Depreciación Acumulada De Instalaciones", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120403", nombre: "Depreciación Acumulada De Otros Bienes Inmuebles", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120404", nombre: "Depreciación Acumulada De Mobiliario Y Equipo De Oficina", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120405", nombre: "Depreciación Acumulada De Maquinaría Y Equipo", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120406", nombre: "Depreciación Acumulada De Equipo De Transporte", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120407", nombre: "Depreciación Acumulada De Herramientas Y Utilerias", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120408", nombre: "Depreciación Acumulada De Otros Equipos", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120501", nombre: "Deterioro De Valor De Terrenos", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120502", nombre: "Deterioro De Valor De Edificaciones", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120503", nombre: "Deterioro De Valor De Instalaciones", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120504", nombre: "Deterioro De Valor De Otros Bienes Inmuebles", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120505", nombre: "Deterioro De Valor De Mobiliario Y Equipo De Oficina", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120506", nombre: "Deterioro De Valor De Maquinaria Y Equipo", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120507", nombre: "Deterioro De Valor De Equipo De Transporte", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120508", nombre: "Deterioro De Valor De Herramientas Y Repuestos", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120509", nombre: "Deterioro De Valor De Otros Equipos", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120510", nombre: "Deterioro De Valor De Instalaciones Arrendadas", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120601", nombre: "Software", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120602", nombre: "Aplicaciones Informáticas", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120603", nombre: "Patentes", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120604", nombre: "Marcas", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120605", nombre: "Concesiones Y Franquicias", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120606", nombre: "Otros Activos Intangibles", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120607", nombre: "Plusvalía Comprada", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120701", nombre: "Amortización Acumulada De Software", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120702", nombre: "Amortización Acumulada De Aplicaciones Informáticas", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120703", nombre: "Amortización Acumulada De Patentes", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120704", nombre: "Amortización Acumulada De Marcas", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120705", nombre: "Amortización Acumulada De Concesiones Y Franquicias", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120706", nombre: "Amortización Acumulada De Otros Activos Intangibles", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120707", nombre: "Amortización Acumulada De Plusvalía Comprada", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120801", nombre: "Deterioro De Valor De Software", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120802", nombre: "Deterioro De Valor De Aplicaciones Informáticas", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120803", nombre: "Deterioro De Valor De Patentes", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120804", nombre: "Deterioro De Valor De Marcas", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120805", nombre: "Deterioro De Valor De Concesiones Y Franquicias", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120806", nombre: "Deterioro De Valor De Otros Activos Intangibles", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120807", nombre: "Deterioro De Valor De Plusvalía Comprada", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120901", nombre: "Inversiones En Terrenos", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "120902", nombre: "Inversiones En Edificaciones", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "121001", nombre: "Depreciación Acumulada De Inversiones En Terrenos", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "121002", nombre: "Depreciación Acumulada De Inversiones En Edificaciones", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "121101", nombre: "Deterioro De Valor De Inversiones En Terrenos", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "121102", nombre: "Deterioro De Valor De Inversiones En Edificaciones", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "121201", nombre: "Inversiones Financieras A Largo Plazo", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "121202", nombre: "Otras Inversiones A Largo Plazo", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "121301", nombre: "Deterioro De Valor De Inversiones A Largo Plazo", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "121302", nombre: "Deterioro De Valor De Otras Inversiones A Largo Plazo", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "121405", nombre: "Préstamos A Accionistas", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "121501", nombre: "Arrendamiento Financiero Por Cobrar", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "121601", nombre: "Activo Por Impuesto Sobre La Renta Diferido", clase: "Activo", tipo_saldo: "deudor" },
  { codigo: "21010101", nombre: "Proveedores Locales", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "21010102", nombre: "Proveedores Del Exterior", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "21010201", nombre: "Acreedores Locales", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "21010202", nombre: "Acreedores Del Exterior", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "21010203", nombre: "Acreedores Varios", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "21010301", nombre: "Documentos Por Pagar A Proveedores Nacionales", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "21010302", nombre: "Documentos Por Pagar A Proveedores Extranjeros", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "21010303", nombre: "Letras De Cambio", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "21010304", nombre: "Pagaré", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "21010305", nombre: "Intereses Por Pagar", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "210104", nombre: "Anticipo De Clientes", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "210105", nombre: "Fondos Ajenos En Custodia", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "210106", nombre: "Documentos Por Cobrar Descontados", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "210107", nombre: "Otras Cuentas Por Pagar", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "210108", nombre: "Accionistas", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "210201", nombre: "Impuesto Sobre La Renta Retenido A Empleados", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "210202", nombre: "Impuesto Sobre La Renta Retenido Por Servicios Eventuales", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "210203", nombre: "Impuesto Sobre La Renta Retenido Por Pago De Dividendos", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "210204", nombre: "Retenciones De Isss Al Trabajador", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "210205", nombre: "Retenciones De Afp Trabajador", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "210206", nombre: "Retención De Ipsfa Trabajador", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "210207", nombre: "Retenciones De Vialidad", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "210208", nombre: "Retenciones Procuraduria General De La Republica", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "210209", nombre: "Retenciones A Empleados Por Préstamos", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "210210", nombre: "Otras Retenciones", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "210301", nombre: "Impuestos Municipales Por Pagar", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "210302", nombre: "Iva Por Pagar", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "210303", nombre: "Pago A Cuenta Por Pagar", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "210304", nombre: "Impuesto Sobre La Renta Por Pagar", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "210305", nombre: "Otros Impuestos Por Pagar", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "210401", nombre: "Nómina Por Pagar", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "210402", nombre: "Comisiones Por Pagar", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "210403", nombre: "Bonificaciones Por Pagar", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "210404", nombre: "Vacaciones Por Pagar", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "210405", nombre: "Aguinaldos Por Pagar", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "210406", nombre: "Isss Cuota Patronal", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "210407", nombre: "Afp Cuota Patronal", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "210408", nombre: "Ipsfa Cuota Patronal", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "210409", nombre: "Insaforp Cuota Patronal", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "210410", nombre: "Indemnizaciones Por Pagar", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "210501", nombre: "Débito Fiscal Contribuyentes", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "210502", nombre: "Débito Fiscal Consumidores Finales", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "210503", nombre: "1% Retenido A Terceros", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "210504", nombre: "1% Percibido A Terceros", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "210601", nombre: "Obligaciones Bajo Arrendamiento Financiero", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "210701", nombre: "Dividendos Por Pagar", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "21080101", nombre: "Valor Nominal De Los Prestamos Bancarios", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "21080102", nombre: "Intereses Por Pagar", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "21080201", nombre: "Valor Nominal De Los Sobregiros Bancarios", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "21080202", nombre: "Intereses Por Pagar", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "21080301", nombre: "Valor Nominal De Los Préstamos Bancarios", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "21080302", nombre: "Intereses Por Pagar", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "210804", nombre: "Otros Préstamos", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "21090101", nombre: "Provisiones Para Garantía De Ventas", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "21090102", nombre: "Otras Provisiones", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "22010101", nombre: "Provision Por Prestación Económica De Retiro Voluntario", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "22010102", nombre: "Otras Provisiones", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "22020101", nombre: "Valor Nominal De Los Préstamos Bancarios", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "22030101", nombre: "Arrendamiento Financiero Por Pagar A Largo Plazo", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "220401", nombre: "Pasivo Por Impuesto Sobre La Renta Diferido", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "220501", nombre: "Otras Cuentas Por Pagar Largo Plazo", clase: "Pasivo", tipo_saldo: "acreedor" },
  { codigo: "31010101", nombre: "Capital Social Mínimo Pagado", clase: "Capital", tipo_saldo: "acreedor" },
  { codigo: "31010102", nombre: "Capital Social Mínimo No Pagado", clase: "Capital", tipo_saldo: "acreedor" },
  { codigo: "31010201", nombre: "Capital Social Variable Pagado", clase: "Capital", tipo_saldo: "acreedor" },
  { codigo: "31010202", nombre: "Capital Social Variable No Pagado", clase: "Capital", tipo_saldo: "acreedor" },
  { codigo: "32010101", nombre: "Reserva Legal", clase: "Capital", tipo_saldo: "acreedor" },
  { codigo: "3203", nombre: "Otras Reservas", clase: "Capital", tipo_saldo: "acreedor" },
  { codigo: "320201", nombre: "Otras Reservas", clase: "Capital", tipo_saldo: "acreedor" },
  { codigo: "33010101", nombre: "Utilidades Acumuladas De Ejercicios Anteriores", clase: "Capital", tipo_saldo: "acreedor" },
  { codigo: "33010102", nombre: "Utilidades Del Presente Ejercicio", clase: "Capital", tipo_saldo: "acreedor" },
  { codigo: "33010201", nombre: "Pérdida De Ejercicios Anteriores", clase: "Capital", tipo_saldo: "acreedor" },
  { codigo: "33010202", nombre: "Pérdida Del Presente Ejercicio", clase: "Capital", tipo_saldo: "acreedor" },
  { codigo: "3401", nombre: "Superávit Por Revaluación", clase: "Capital", tipo_saldo: "acreedor" },
  { codigo: "410101", nombre: "Costo Por Venta De Bienes", clase: "Costo", tipo_saldo: "deudor" },
  { codigo: "410102", nombre: "Costo Por La Prestación De Servicios", clase: "Costo", tipo_saldo: "deudor" },
  { codigo: "410103", nombre: "Costo Por Intereses", clase: "Costo", tipo_saldo: "deudor" },
  { codigo: "410104", nombre: "Costo Por Regalias", clase: "Costo", tipo_saldo: "deudor" },
  { codigo: "410105", nombre: "Costo Por Dividendos", clase: "Costo", tipo_saldo: "deudor" },
  { codigo: "410106", nombre: "Costo Por Comisiones", clase: "Costo", tipo_saldo: "deudor" },
  { codigo: "420101", nombre: "Sueldos Y Salarios Personal", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420102", nombre: "Horas Extras Personal", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420103", nombre: "Horas Extras Personal Eventual", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420104", nombre: "Vacaciones Personal", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420105", nombre: "Aguinaldos Personal", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420106", nombre: "Indemnizaciones Personal", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420107", nombre: "Aportación Patronal Isss", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420108", nombre: "Aportación Patronal Afp", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420109", nombre: "Aportación Patronal Ipsfa", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420110", nombre: "Insaforp", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420111", nombre: "Prestación Económica Por Retiro Voluntario", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420112", nombre: "Gratificaciones Y Bonificaciones", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420113", nombre: "Atención Al Personal", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420114", nombre: "Capacitación A Empleados", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420115", nombre: "Uniformes", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420116", nombre: "Viáticos", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420117", nombre: "Alimentación", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420118", nombre: "Gastos De Viaje Y Viáticos", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420119", nombre: "Atención A Terceros", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420120", nombre: "Reparaciones Y Repuestos P/Vehículos", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420121", nombre: "Combustibles Y Lubricantes", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420122", nombre: "Depreciaciones", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420123", nombre: "Mantenimiento Y Reparación De Equipo De Oficina", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420124", nombre: "Teléfono Y Correo", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420125", nombre: "Servicios De Internet", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420126", nombre: "Energía Eléctrica", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420127", nombre: "Agua", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420128", nombre: "Alquileres", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420129", nombre: "Impuestos Municipales", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420130", nombre: "Auditoría Financiera Y Fiscal", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420131", nombre: "Matrículas De Comercio", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420132", nombre: "Trámites Cnr", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420133", nombre: "Trámites Aduanales Y Manejo Importacion", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420134", nombre: "Seguros Y Fianzas", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420135", nombre: "Papeleria Y Utiles", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420136", nombre: "Donativos Y Contribuciones", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420137", nombre: "Honorarios Por Asesoría", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420138", nombre: "Honorarios A Terceros", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420139", nombre: "Publicaciones Y Anuncios", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420140", nombre: "Publicidad Y Promociones", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420141", nombre: "Perfiles Profesionales-Outsourcing", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420142", nombre: "Licencias Y Sistemas", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420143", nombre: "Implementos De Limpieza", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420144", nombre: "Taxí, Bus Y Encomiendas", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420145", nombre: "Otros Materiales", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420146", nombre: "Higiene Y Seguridad Industrial", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420147", nombre: "Botiquín", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420148", nombre: "Impuesto A La Seguridad", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420149", nombre: "Depreciación De Edificaciones", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420150", nombre: "Depreciación De Instalaciones", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420151", nombre: "Depreciación De Otros Bienes Inmuebles", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420152", nombre: "Depreciación De Mobiliario Y Equipo De Oficina", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420153", nombre: "Depreciación De Maquinaría Y Equipo", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420154", nombre: "Depreciación De Equipo De Transporte", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420155", nombre: "Depreciación De Herramientas Y Utilerias", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420156", nombre: "Depreciación De Otros Equipos", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420157", nombre: "Depreciación De Instalaciones Arrendadas", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420158", nombre: "Amortización De Software", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420159", nombre: "Amortización De Aplicaciones Informáticas", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420160", nombre: "Amortización De Patentes", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420161", nombre: "Amortización De Marcas", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420162", nombre: "Amortización De Concesiones Y Franquicias", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420163", nombre: "Amortización De Otros Activos Intangibles", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420164", nombre: "Amortización De Plusvalía Comprada", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420165", nombre: "Suscripciones", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420166", nombre: "Chequera", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420167", nombre: "Comisiones Bancarias", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420168", nombre: "Varios", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420169", nombre: "Servicios De Limpieza", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420170", nombre: "Otros Gastos", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420171", nombre: "Gastos No Deducibles", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420201", nombre: "Sueldos Y Salarios Personal Fijo", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420202", nombre: "Sueldos Y Salarios Eventuales", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420203", nombre: "Horas Extras Personal Fijo", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420204", nombre: "Horas Extras Personal Eventual", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420205", nombre: "Vacaciones Personal Fijo", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420206", nombre: "Aguinaldos Personal Fijo", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420207", nombre: "Indemnizaciones Personal Fijo", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420208", nombre: "Aportación Patronal Isss", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420209", nombre: "Aportación Patronal Afp", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420210", nombre: "Insaforp", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420211", nombre: "Prestación Económica Por Retiro Voluntario", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420212", nombre: "Gratificaciones Y Bonificaciones", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420213", nombre: "Atención Al Personal", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420214", nombre: "Capacitación A Empleados", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420215", nombre: "Uniformes", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420216", nombre: "Viáticos", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420217", nombre: "Alimentación", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420218", nombre: "Gastos De Viaje Y Viáticos", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420219", nombre: "Atención A Terceros", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420220", nombre: "Reparaciones Y Repuestos P/Vehiculos", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420221", nombre: "Combustibles Y Lubricantes", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420222", nombre: "Depreciaciones", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420223", nombre: "Reparación De Equipo De Oficina", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420224", nombre: "Teléfono Y Correo", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420225", nombre: "Servicios De Internet", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420226", nombre: "Energía Eléctrica", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420227", nombre: "Agua", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420228", nombre: "Alquileres", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420229", nombre: "Impuestos Municipales", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420230", nombre: "Auditoría Financiera Y Fiscal", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420231", nombre: "Matrículas De Comercio", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420232", nombre: "Trámites Cnr", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420233", nombre: "Trámites Aduanales Y Manejo Importacion", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420234", nombre: "Seguros Y Fianzas", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420235", nombre: "Papelería Y Útiles", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420236", nombre: "Donativos Y Contribuciones", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420237", nombre: "Honorarios Por Asesoría", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420238", nombre: "Honorarios A Terceros", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420239", nombre: "Publicaciones Y Anuncios", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420240", nombre: "Publicidad Y Promociones", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420241", nombre: "Perfiles Profesionales", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420242", nombre: "Licencias Y Sistemas", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420243", nombre: "Implementos De Limpieza", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420244", nombre: "Taxí, Bus Y Encomiendas", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420245", nombre: "Otros Materiales", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420246", nombre: "Higiene Y Seguridad Industrial", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420247", nombre: "Botiquín", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420248", nombre: "Impuesto A La Seguridad", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420249", nombre: "Depreciación De Edificaciones", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420250", nombre: "Depreciación De Instalaciones", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420251", nombre: "Depreciación De Otros Bienes Inmuebles", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420252", nombre: "Depreciación De Mobiliario Y Equipo De Oficina", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420253", nombre: "Depreciación De Maquinaría Y Equipo", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420254", nombre: "Depreciación De Equipo De Transporte", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420255", nombre: "Depreciación De Herramientas Y Utilerias", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420256", nombre: "Depreciación De Otros Equipos", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420257", nombre: "Depreciación De Instalaciones Arrendadas", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420258", nombre: "Amortización De Programas De Software", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420259", nombre: "Amortización De Aplicaciones Informáticas", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420260", nombre: "Amortización De Patentes", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420261", nombre: "Amortización De Marcas", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420262", nombre: "Amortización De Concesiones Y Franquicias", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420263", nombre: "Amortización De Otros Activos Intangibles", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420264", nombre: "Amortización De Plusvalía Comprada", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420265", nombre: "Cuentas Incobrables", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420266", nombre: "Servicios De Limpieza", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420267", nombre: "Gastos No Deducibles", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420268", nombre: "Suscripciones", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420269", nombre: "Comisiones Bancarias", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "420270", nombre: "Varios", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "430101", nombre: "Intereses", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "43010201", nombre: "Por Otorgamiento De Créditos Y Préstamos", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "43010202", nombre: "Rechazos De Cheque", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "43010203", nombre: "Certificación De Cheque", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "43010204", nombre: "Por Operaciones De Transferencias", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "43010205", nombre: "Por Pagos De Planilla", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "43010206", nombre: "Otras Comisiones", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "430103", nombre: "Otros Gastos Financieros", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "430201", nombre: "Gasto Por Impuesto Sobre La Renta Corriente", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "430202", nombre: "Gasto Por Impuesto Sobre La Renta Extraordinario", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "430301", nombre: "Pérdida En Venta De Propiedades Planta Y Equipo", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "430302", nombre: "Pérdida En Venta De Activos Intangibles", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "430303", nombre: "Pérdida En Venta Por Inversiones En Valores", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "430401", nombre: "Deterioro De Valor De Los Activos", clase: "Gasto", tipo_saldo: "deudor" },
  { codigo: "510101", nombre: "Ingresos Por Venta De Bienes", clase: "Ingreso", tipo_saldo: "acreedor" },
  { codigo: "510102", nombre: "Ingresos Por La Prestación De Servicios", clase: "Ingreso", tipo_saldo: "acreedor" },
  { codigo: "510103", nombre: "Ingresos Por Intereses", clase: "Ingreso", tipo_saldo: "acreedor" },
  { codigo: "510104", nombre: "Ingresos Por Regalías", clase: "Ingreso", tipo_saldo: "acreedor" },
  { codigo: "510105", nombre: "Ingresos Por Dividendos", clase: "Ingreso", tipo_saldo: "acreedor" },
  { codigo: "510106", nombre: "Ingresos Por Comisiones", clase: "Ingreso", tipo_saldo: "acreedor" },
  { codigo: "5102", nombre: "Ingresos Por Inversiones Y Valores", clase: "Ingreso", tipo_saldo: "acreedor" },
  { codigo: "510201", nombre: "Dividendos", clase: "Ingreso", tipo_saldo: "acreedor" },
  { codigo: "510202", nombre: "Intereses Bancarios", clase: "Ingreso", tipo_saldo: "acreedor" },
  { codigo: "510203", nombre: "Intereses Sobre Inversiones", clase: "Ingreso", tipo_saldo: "acreedor" },
  { codigo: "510204", nombre: "Otros Ingresos Por Inversiones En Valores", clase: "Ingreso", tipo_saldo: "acreedor" },
  { codigo: "52010101", nombre: "Ganancia En Venta De Propiedades Planta Y Equipo", clase: "Ingreso", tipo_saldo: "acreedor" },
  { codigo: "52010102", nombre: "Ganancia En Venta De Activos Intangibles", clase: "Ingreso", tipo_saldo: "acreedor" },
  { codigo: "52010103", nombre: "Ganancia En Venta Por Inversiones En Valores", clase: "Ingreso", tipo_saldo: "acreedor" },
  { codigo: "520201", nombre: "Indemnizaciones De Seguro Recibidas", clase: "Ingreso", tipo_saldo: "acreedor" },
  { codigo: "520202", nombre: "Otros Ingresos Extraordinarios", clase: "Ingreso", tipo_saldo: "acreedor" },
];

// Se usa el mismo catálogo completo para empresas comerciales y de servicio.
export function catalogoPorTipo(tipo) {
  return CATALOGO_COMPLETO;
}