// Nombres de las cuentas de mayor (nivel 4 dígitos) de tu catálogo,
// usados para agrupar/acumular el Libro Mayor. Si el código no está
// en esta lista (por ejemplo con otro catálogo), se usa el código solo.

export const CUENTAS_MAYOR_4_DIGITOS = {
  "1101": "Efectivo Y Equivalentes",
  "1102": "Inversiones Financieras A Corto Plazo",
  "1103": "Deudores Comerciales Y Otras Cuentas Por Cobrar",
  "1104": "Provisión Para Cuentas Incobrables",
  "1105": "Anticipo Del Impuesto Sobre La Renta",
  "1106": "Iva Crédito Fiscal",
  "1107": "Inventarios",
  "1108": "Deterioro De Valor De Los Inventarios",
  "1109": "Gastos Pagados Por Anticipado",
  "1201": "Cuentas Por Cobrar A Largo Plazo",
  "1202": "Depósito En Garantía",
  "1203": "Propiedades Planta Y Equipo",
  "1204": "Depreciación Acumulada De Propiedades Planta Y Equipo",
  "1205": "Deterioro De Valor De Propiedades Planta Y Equipo",
  "1206": "Activos Intangibles",
  "1207": "Amortización Acumulada De Intangibles",
  "1208": "Deterioro De Valor De Activos Intangibles",
  "1209": "Propiedades De Inversión",
  "1210": "Depreciación Acumulada De Propiedades De Inversión",
  "1211": "Deterioro De Valor De Propiedades De Inversion",
  "1212": "Inversiones Financieras A La Largo Plazo",
  "1213": "Deterioro De Valor De Inversiones A Largo Plazo",
  "1214": "Partes Relacionadas A Largo Plazo",
  "1215": "Arrendamiento Financiero Por Cobrar",
  "1216": "Activo Por Impuesto Sobre La Renta Diferido",
  "2101": "Deudas Comerciales Y Otras Cuentas Por Pagar",
  "2102": "Retenciones Por Pagar",
  "2103": "Impuestos Por Pagar",
  "2104": "Beneficios A Empleados Por Pagar",
  "2105": "Débito Fiscal Iva",
  "2106": "Obligaciones Bajo Arrendamiento Financiero",
  "2107": "Dividendos Por Pagar",
  "2108": "Deudas Financieras A Corto Plazo",
  "2109": "Provisiones A Corto Plazo",
  "2201": "Provisiones A Largo Plazo",
  "2202": "Préstamos A Largo Plazo",
  "2203": "Obligaciones Bajo Arrendamiento Financiero",
  "2204": "Pasivo Por Impuesto Sobre La Renta Diferido",
  "2205": "Cuentas Por Pagar A Largo Plazo",
  "3101": "Capital Social",
  "3201": "Reservas De Capital",
  "3202": "Reserva Legal",
  "3203": "Otras Reservas",
  "3301": "Resultados Acumulados",
  "3401": "Superávit Por Revaluación",
  "4101": "Costo De Venta",
  "4201": "Gastos De Administracion",
  "4202": "Gastos De Venta",
  "4301": "Gastos Financieros",
  "4302": "Gasto Por Impuesto A Las Ganancias",
  "4303": "Pérdida En Ventas De Activos",
  "4304": "Deterioro Y Pérdida De Valor",
  "5101": "Ingresos De Actividades Ordinarias",
  "5102": "Ingresos Por Inversiones Y Valores",
  "5201": "Ingresos No Operacionales",
  "5202": "Otros Ingresos No Operacionales",
  "6101": "Pérdidas Y Ganacias",
};

export function nombreCuentaMayor(codigo4) {
  return CUENTAS_MAYOR_4_DIGITOS[codigo4] || null;
}